os: linux
language: php
php:
  - 7.4
before_install:
  - openssl aes-256-cbc -K $encrypted_e60fa7ed95bb_key -iv $encrypted_e60fa7ed95bb_iv
    -in .travis/deploy_rsa.enc -out .travis/deploy_rsa -d
  - eval "$(ssh-agent -s)"
  - cp .travis/deploy_rsa ~/.ssh/id_rsa
  - chmod 600 ~/.ssh/id_rsa
  - ssh-add ~/.ssh/id_rsa
deploy:
  provider: script
  cleanup: true
  script: bash .travis/deploy.sh
  on:
    branch: master
before_script:
  - composer install
addons:
  ssh_known_hosts:
    secure: SDVDBzF8Mn7B1BWG0dpKWSmSNhf0g1n80RFNWn2Rue6Iun22JGwFmpF2UOwBC7kfaekMP9hPQO2s5MpF5xanjC2b16TZN6aT0K9agF77idbA2gX04aZ3c8cbU97gfLZbzH8V8ZASGLG6WpfbwLVtKvcuxdFSCFwphK+j0OIp4WLwbpZp4u1cFlDPFiNhEJwOE1agHQY+8DmFosc+gc4tIDqWJfFkpbf49jpMuHkH7Qb/owovMW0QC4X3QPorvVCDTBYhjad5ZAXkAgq6iXkvw3rI4Cra9tFQF2Iljh0bqwW8y1fsr+qihO9YXu7w2BatGaNwg50SvweIZv03y620DCKebGC7yGEz0dBQlrU1lWZx8nZhgpIrO13j1eW1cAbOosSopFzY9pXHkH5ZggmQX7UB1uqPpct+tooG2LzRdQ8/MBLWjRWXAbsIExYSWgMN2feug63D6/0qay3YJf6zOcUn5TRz9xlNvMs6F3h1q6xraGyCLu2CYHx6MmiQEd8w/lkX+sj6WaZ8/VtSheY4WydKiVNcn19X6sQcRvxUx8ItVGm7yIO5DPsxlv75wZjUGfPAprxCOC4ryk4kfWGXQdEbZxu6UH3+D1t5crUD/Jrtln5C1IVLUdSi3zvSFLxBmOdGuLq4BvcoUTGe4/1LpEfkcJ0+6bJGBDztwERhCEw=
