version: '3'

services:
 php:
  build: .
  container_name: php
  volumes:
   - ./:/var/www/html/
   - .docker/php:/usr/local/etc/php/custom.d
 nginx-server:
  image: nginx:1.17
  container_name: nginx-server
  ports:
    - "${APP_PORT}:80"
  volumes:
    - ./:/var/www/html
    - .docker/nginx/log:/var/www/log
    - .docker/nginx/site.conf:/etc/nginx/conf.d/default.conf
  depends_on:
    - php

